#linear regression, Ridge and lasso regression

In [75]:
#House pricing dataset
from sklearn.datasets import load_boston

In [76]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [77]:
df=load_boston()

C:\Users\vishwanth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include

In [78]:
df

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [79]:
dataset=pd.DataFrame(df.data)

In [80]:
dataset.columns = df.feature_names
print(dataset.head())

      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33  


In [81]:
dataset['Price']= df.target

In [82]:
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [83]:
## dividing the dataset in to train independent and dependent features
X = dataset.iloc[:,:-1]#slipping the last feature and it it independent feature
y=dataset.iloc[:,-1]# dependent features

In [84]:
# best way is train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.33, random_state = 45 )

In [85]:
#Linear Regression
#in cross validation : if you do 100 data of validation, 10 would be test data and remainng would be train data

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
mse= cross_val_score(lin_reg, X_train, y_train,scoring = 'neg_mean_squared_error', cv=5)

In [86]:
mean_mse= np.mean(mse)
print(mean_mse)

-24.986002378537876


In [87]:
lin_reg.predict(X_test)

array([ 9.92906761, 23.19355281, 24.93598605, 21.41720278, 35.05091695,
       14.42714724, 19.47196912, 19.02479677, 27.70492906, 17.43533962,
       14.55996083, 20.09768095, 36.23642686, 23.85263362, 16.37370964,
       20.13677856, 28.28233733, 11.3102671 , 15.75601787, 22.36854058,
       22.52918905, 13.88080015, 19.65833525, 32.27563853, 22.54886025,
       27.67116245, 23.05129758,  7.36948058, 26.19752793, 19.32714394,
       21.28700766,  8.44762766, 27.94083043, 24.89303298, 35.88363605,
       25.51425146, 39.42517846,  2.40253564, 31.66422292, 32.61836938,
       19.50379089, 21.99344272, 17.20720621, 31.20945279, 18.88445312,
       18.38378137, 28.68022182, 28.18480824, 18.48688416, 22.30774791,
       42.86830816, 16.03085832, 27.83922694, 35.24245441, 16.38504945,
       31.43698108,  5.97177914, 13.61305791, 18.81316829, 19.79335813,
       14.29555186, 18.260332  , 37.0595802 , 35.74643172, 18.04630626,
       12.99768605, 38.78329914, 36.28312197, 14.6417183 , 19.54

In [88]:
#Ridge Regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [89]:
ridge =Ridge()
params = {'alpha':[1e-15, 1e-10, 1e-8, 1e-3, 1e-2, 1, 5, 10, 20]}

In [90]:
ridge_regressor = GridSearchCV(ridge, params, scoring='neg_mean_squared_error',cv=5)
ridge_regressor.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

In [91]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 0.01}
-24.97946122842789


In [92]:
ridge_regressor.predict(X_test)

array([ 9.91497195, 23.20040849, 24.93262431, 21.41502905, 35.05400181,
       14.42955284, 19.48323085, 19.02180568, 27.6903097 , 17.44187342,
       14.56610394, 20.10154231, 36.23459547, 23.84289545, 16.35943743,
       20.1329436 , 28.27619073, 11.30676361, 15.75352847, 22.38937016,
       22.53824459, 13.90279217, 19.66954128, 32.26865614, 22.53012475,
       27.67853254, 23.05686671,  7.37263327, 26.18588916, 19.33324443,
       21.28418979,  8.44738846, 27.9466688 , 24.89118825, 35.87465017,
       25.51588978, 39.41756544,  2.38165589, 31.66515854, 32.61148822,
       19.51996973, 21.98184503, 17.21334124, 31.21394115, 18.8859672 ,
       18.38134685, 28.67091703, 28.17931254, 18.48805017, 22.30082627,
       42.86229145, 16.05380923, 27.8355986 , 35.23806202, 16.39723581,
       31.43531475,  5.97310488, 13.6122958 , 18.81724541, 19.79335576,
       14.29559582, 18.26134679, 37.0543987 , 35.75211584, 18.03063268,
       12.99888172, 38.77296441, 36.27310411, 14.65123832, 19.55

In [93]:
#Lasso Regression
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
Lasso =Lasso()

params ={'alpha': [1e-15, 1e-10,1e-8, 1e-3, 1e-2, 5,10, 20, 30, 35, 40, 45, 50, 55, 80]}
lasso_regressor = GridSearchCV(Lasso, params, scoring='neg_mean_squared_error', cv=10)
lasso_regressor.fit(X_train, y_train)


C:\Users\vishwanth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.405e+03, tolerance: 2.576e+00
  model = cd_fast.enet_coordinate_descent(
C:\Users\vishwanth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.138e+03, tolerance: 2.351e+00
  model = cd_fast.enet_coordinate_descent(
C:\Users\vishwanth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, c

GridSearchCV(cv=10, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 5, 10, 20,
                                   30, 35, 40, 45, 50, 55, 80]},
             scoring='neg_mean_squared_error')

In [94]:
lasso_regressor.best_params_
lasso_regressor.best_score_

-24.778672540289957

In [95]:
y_pred = lasso_regressor.predict(X_test)
y_pred

array([ 9.9009069 , 23.20932975, 24.92817085, 21.41321054, 35.05513177,
       14.43314389, 19.49589028, 19.02142642, 27.67515674, 17.44924445,
       14.57065329, 20.10619358, 36.23107608, 23.83366514, 16.3457166 ,
       20.12956454, 28.27239887, 11.30066762, 15.74967123, 22.41342289,
       22.55062253, 13.92879756, 19.68313655, 32.25993238, 22.51148598,
       27.68813127, 23.06296907,  7.37571223, 26.17668747, 19.34051137,
       21.28299792,  8.44648193, 27.95340295, 24.88966718, 35.86787181,
       25.51746505, 39.3952581 ,  2.35955583, 31.66671394, 32.60454741,
       19.52409857, 21.95697525, 17.21978335, 31.21909982, 18.88956133,
       18.3777769 , 28.66130099, 28.17442436, 18.49115561, 22.29859065,
       42.85485599, 16.08076367, 27.83225014, 35.2323088 , 16.41141127,
       31.43345306,  5.9739641 , 13.61312507, 18.8224199 , 19.79577934,
       14.2948453 , 18.2618753 , 37.04931174, 35.75965358, 18.0137697 ,
       13.00319904, 38.76204259, 36.26435315, 14.66764908, 19.56

In [96]:
from sklearn.metrics import r2_score
r2_score =r2_score(y_pred, y_test)

In [97]:

#logistic regression
from sklearn.linear_model import LogisticRegression

In [98]:
from sklearn.datasets import load_breast_cancer


In [99]:
df = load_breast_cancer()
##independent features
X=pd.DataFrame(df['data'], columns= df['feature_names'])

In [100]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [101]:
#Dependent feature
y=pd.DataFrame(df['target'], columns = ['Target'])
y

Target
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

In [102]:
#check whether datset is balanced or imbalanced 
#if the data is imbalanced we have to work on off-sampling
#here we have to check 'y'
y['Target'].value_counts()

1    357
0    212
Name: Target, dtype: int64

In [103]:
## Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.32, random_state=41)




In [104]:
params=[{'C': [1,5,10]},{'max_iter':[100,400]}]

In [105]:
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression(C=100, max_iter=100)

In [106]:
from sklearn.model_selection import GridSearchCV
GridSearchCV(model1, param_grid = params, scoring='f1', cv=5)

GridSearchCV(cv=5, estimator=LogisticRegression(C=100),
             param_grid=[{'C': [1, 5, 10]}, {'max_iter': [100, 400]}],
             scoring='f1')

In [107]:
model1.fit(X_train, y_train)

C:\Users\vishwanth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\vishwanth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=100)

In [108]:
model1.best_params_

AttributeError: 'LogisticRegression' object has no attribute 'best_params_'

In [114]:
model1.best_score_

AttributeError: 'LogisticRegression' object has no attribute 'best_score_'

In [115]:
y_pred = model1.predict(X_test)

In [109]:
y_pred

array([ 9.9009069 , 23.20932975, 24.92817085, 21.41321054, 35.05513177,
       14.43314389, 19.49589028, 19.02142642, 27.67515674, 17.44924445,
       14.57065329, 20.10619358, 36.23107608, 23.83366514, 16.3457166 ,
       20.12956454, 28.27239887, 11.30066762, 15.74967123, 22.41342289,
       22.55062253, 13.92879756, 19.68313655, 32.25993238, 22.51148598,
       27.68813127, 23.06296907,  7.37571223, 26.17668747, 19.34051137,
       21.28299792,  8.44648193, 27.95340295, 24.88966718, 35.86787181,
       25.51746505, 39.3952581 ,  2.35955583, 31.66671394, 32.60454741,
       19.52409857, 21.95697525, 17.21978335, 31.21909982, 18.88956133,
       18.3777769 , 28.66130099, 28.17442436, 18.49115561, 22.29859065,
       42.85485599, 16.08076367, 27.83225014, 35.2323088 , 16.41141127,
       31.43345306,  5.9739641 , 13.61312507, 18.8224199 , 19.79577934,
       14.2948453 , 18.2618753 , 37.04931174, 35.75965358, 18.0137697 ,
       13.00319904, 38.76204259, 36.26435315, 14.66764908, 19.56

In [111]:
from sklearn.metrics import confusion_matrix, classification_report

In [112]:
confusion_matrix(y_test, y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [183, 167]

In [113]:
accuracy_score(y_test, y_pred)

NameError: name 'accuracy_score' is not defined

In [ ]:
(y_test,y_predprint(classification)))