In [4]:
#one d array
#numpy.array(object, dtype=none,copy=true,order=none,subok=false,ndim=0)
import numpy as np
a=np.array([1,2])
a

array([1, 2])

In [6]:
#2d array
import numpy as np
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
#3d array
import numpy as np
a=np.array([[[1,2],[3,4],[4,5]]])
a


array([[[1, 2],
        [3, 4],
        [4, 5]]])

In [2]:
#numpy.dtype(object, align, copy)
#shape()
g=np.array([1,2,3,4],dtype= int)
g.shape


(4,)

In [11]:
#RESIZE THE NARRAY
import numpy as np
h=np.array([[8,7,5,6],[3,4,7,1]])
h.shape = (2,4)
print(h)

[[8 7 5 6]
 [3 4 7 1]]


In [7]:
#transpose of the matrix
import  numpy as np
d=np.array([[2,3,4],[5,6,7],[7,8,4]])
print('array x:/n', d)
print('the transpose of the array d is \n',d.T)

array x:/n [[2 3 4]
 [5 6 7]
 [7 8 4]]
the transpose of the array d is 
 [[2 5 7]
 [3 6 8]
 [4 7 4]]


In [13]:
import numpy as np
g=np.empty((3,2),dtype= int)
g

array([[ 376599412, 1912602624],
       [        92, 1818430426],
       [1836282721, 1869116517]])

In [18]:
#an array of evenly spaced numbers
import numpy as np
a=np.arange(1,10)
b=np.arange(1,22)
print(a)
b

[1 2 3 4 5 6 7 8 9]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [14]:
import numpy as np
v=np.ones((3,3), dtype=int)
v

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
#array of zeros 
import numpy as np
c=np.zeros(12)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
#array of zeros with including dtype and warning function
import numpy as np
import warnings
warnings.filterwarnings('ignore')
s=np.zeros(8 , dtype=float)
s


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
#convert list in to array
v=['name',12,3.3,454]
d=np.array(v)
d

array(['name', '12', '3.3', '454'], dtype='<U4')

In [37]:
#array from list to tuples
import numpy as np
f=[(1,2,3.3),[4,5,6,7]]
b=np.asarray(f)
b

array([(1, 2, 3.3), list([4, 5, 6, 7])], dtype=object)

In [38]:
#slicing in numpy 
#numpy.arange(start, stop, step, dtype)
a=np.arange(13)
print(a)
s=slice(2,3,4.5)
a[2]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


2

In [5]:
#sclicing
import numpy as np
d=np.array([[1,2,3],[4,5,6],[7,8,9],[5,6,3]])
print('our array is :')
print(d)
print('/n')
#this returns the array in secound column
print('the items in secound coulmn are')
print(d[...,1])
print('\n')
#now secound row
print('the items in secound row')
print(d[1,...])
print('/n')
#all items in column in 1:
print('the coulmn items one are:')
print(d[...,1:])
print('/n')
print('the row items one are:')
print(d[:1,...])
print('/n')
print('the row items one are:')
print(d[1:,:1,...])
print('/n')

our array is :
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 6 3]]
/n
the items in secound coulmn are
[2 5 8 6]


the items in secound row
[4 5 6]
/n
the coulmn items one are:
[[2 3]
 [5 6]
 [8 9]
 [6 3]]
/n
the row items one are:
[[1 2 3]]
/n
the row items one are:
[[4]
 [7]
 [5]]
/n


In [34]:
h=np.arange(4,40,2, int)
print('the array in given below in a range is ',h)

the array in given below in a range is  [ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [15]:
f=np.arange(13)
print(f)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
#linespace
import numpy as np
s=np.linspace(10,3,5)
print('the array of the given range is :',s)
#endpoint set to false
f=np.linspace(12,3,4,endpoint=False)
f
#find the restep value
import numpy as np
f=np.linspace(1,2,3, retstep=True)
print(f)


the array of the given range is : [10.    8.25  6.5   4.75  3.  ]
(array([1. , 1.5, 2. ]), 0.5)


In [51]:
import numpy as np
s=np.arange(14)
b=s[1 : 13 : 3]
b

array([ 1,  4,  7, 10])

In [27]:
#numpy.logspace(start,stop, num, endpoint, base, dtype)
import numpy as np
d=np.logspace(1, 30, num=5)
d

array([1.00000000e+01, 1.77827941e+08, 3.16227766e+15, 5.62341325e+22,
       1.00000000e+30])

In [29]:
#set base of logspace to 2 and endpoint is true
import numpy as np
g=np.logspace(1,15,num=5,base=2,endpoint = True)
g

array([2.00000000e+00, 2.26274170e+01, 2.56000000e+02, 2.89630938e+03,
       3.27680000e+04])

In [51]:
#advanced indexing: retunrs copy of the data, it is used when selection object from narray is non-tuple object with on eint or boolean value
#int indexing
import numpy as np
s=np.array([[2,3,4],[5,6,7],[9,6,5],[3,4,1]])
print('the array used for array indexing :')
print(s)
y=s[[0,1,2,3],[0,1,0,0]]
print('the output is :')
print(y)
rows=np.array([[0],[1]])
columns=np.array([[0,1],[0,1]])
f=s[rows,columns]
print('the corner element of the array is: ',f)



the array used for array indexing :
[[2 3 4]
 [5 6 7]
 [9 6 5]
 [3 4 1]]
the output is :
[2 6 9 3]
the corner element of the array is:  [[2 3]
 [5 6]]


In [62]:
#adding of two array in numpy
a=np.array([1.1,2.3,4,5,67,898])
b=np.array([20,20,30,40,50,60])
c= np.ravel([a + b])
np.ravel(c)

array([ 21.1,  22.3,  34. ,  45. , 117. , 958. ])

In [14]:
#boolean indexing: it is used for the condition using comparision operator or some other operator
import numpy as np
g=([[2,3,4],[4,5,6],[8,9,2]])
print('the array is ')
print('/n')
print(g)
#items greater than 4
print('items more than 4 are')
g[g>=4]

the array is 
/n
[[2, 3, 4], [4, 5, 6], [8, 9, 2]]
items more than 4 are


TypeError: '>=' not supported between instances of 'list' and 'int'

In [54]:
#complement operator
import numpy as np
f=np.array([2,3,4,np.nan,5, np.nan])
print('After omiting the Nan value is')
print(f[~np.isnan(f)])

After omiting the Nan value is
[2. 3. 4. 5.]


In [55]:
import numpy as np
l=np.arange(0,20,5)
print(l.shape)




(4,)


In [75]:
#Trignometry in numpy
import numpy as np
l=np.array([10,20,40,50,40])
print('sine of different angles')
print(np.sin(l))
print(np.cos(l))
print(np.tan(l))
print(np.tan(l)**2)


sine of different angles
[-0.54402111  0.91294525  0.74511316 -0.26237485  0.74511316]
[-0.83907153  0.40808206 -0.66693806  0.96496603 -0.66693806]
[ 0.64836083  2.23716094 -1.11721493 -0.27190061 -1.11721493]
[0.42037176 5.00488909 1.2481692  0.07392994 1.2481692 ]


In [58]:
#to remove the complex value from an array
import numpy as np
s=np.array([1,2,56,3+8j])
print(s[np.iscomplex(s)])


[3.+8.j]


In [97]:
#arranging arrays and shaping in to matrix
import numpy as np
a=np.arange(25,dtype=float).reshape(5,5)
print('first array')
a


first array


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [104]:
print('secound array')
h=np.array([1,2,3,4,5])
print(h)

secound array
[1 2 3 4 5]


In [105]:
print('add two arrays')
print(np.add(a,h))



add two arrays
[[ 1.  3.  5.  7.  9.]
 [ 6.  8. 10. 12. 14.]
 [11. 13. 15. 17. 19.]
 [16. 18. 20. 22. 24.]
 [21. 23. 25. 27. 29.]]


In [114]:
print('subtraction of two arrays')
print(np.subtract(a,h))
print('mul of two arrays')
print(np.multiply(a,h))
print('dividing of two arrays')
print(np.divide(a,h))


subtraction of two arrays
[[-1. -1. -1. -1. -1.]
 [ 4.  4.  4.  4.  4.]
 [ 9.  9.  9.  9.  9.]
 [14. 14. 14. 14. 14.]
 [19. 19. 19. 19. 19.]]
mul of two arrays
[[  0.   2.   6.  12.  20.]
 [  5.  12.  21.  32.  45.]
 [ 10.  22.  36.  52.  70.]
 [ 15.  32.  51.  72.  95.]
 [ 20.  42.  66.  92. 120.]]
dividing of two arrays
[[ 0.          0.5         0.66666667  0.75        0.8       ]
 [ 5.          3.          2.33333333  2.          1.8       ]
 [10.          5.5         4.          3.25        2.8       ]
 [15.          8.          5.66666667  4.5         3.8       ]
 [20.         10.5         7.33333333  5.75        4.8       ]]


In [130]:
import numpy as np
s=np.array([[[2,9,6,7],[3,6,8,3],[1,5,8,3]]])
print('or array is ')
print(s)
print('aplying a min function again:')
print(np.min(a,0))
print(np.max(h,0))

or array is 
[[[2 9 6 7]
  [3 6 8 3]
  [1 5 8 3]]]
aplying a min function again:
[0. 1. 2. 3. 4.]
5


In [131]:
import numpy as np
arr=np.array([1,3,5,30],dtype=float)
g=arr.itemsize
g

8

In [137]:
#broadcasting
#3.rules:a)should same shape.2)should have same no of dimensions. 3)length of the dimension equal or less than 1.3)array with  few dimension can be appended with '1 in it's shape
#np.sqrt()method
import numpy as np
arr1=np.sqrt([1,2,3,4,54,4,44,4])
arr2=np.sqrt([5,6.7,34,65,23,90,42])
print("squareroot of arr1: ",arr1)
print("squareroot of array2: ", arr2)


squareroot of arr1:  [1.         1.41421356 1.73205081 2.         7.34846923 2.
 6.63324958 2.        ]
squareroot of array2:  [2.23606798 2.58843582 5.83095189 8.06225775 4.79583152 9.48683298
 6.4807407 ]


In [15]:
#nupy sum() method : axis =0(up, down), axis=1(left, right)
import numpy as np
ar=[20,53,233,367,12,35]
print("sum of the arr",np.sum(ar,dtype=int))
print('sum of the arr(float32):',np.sum(ar,dtype=float))
print('/n sum of arr(axis=0)', np.sum(ar, axis=0))


sum of the arr 720
sum of the arr(float32): 720.0
/n sum of arr(axis=0) 720


In [155]:
import numpy as np
y=np.arange(10).reshape(2,5)
print(k)


<module 'numpy' from 'c:\\users\\pc\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\numpy\\__init__.py'>


In [69]:
#interator:providse an iterator object 'numpy.nditer'
import numpy as np
d=np.arange(3,20,4)
d=d.reshape(5,1)
print('the original array is ', d)
print('/n')
print('the modified array is: ')
for i in np.nditer(d):
    print(i)


the original array is  [[ 3]
 [ 7]
 [11]
 [15]
 [19]]
/n
the modified array is: 
3
7
11
15
19


In [96]:
import numpy as np
d=np.array([[3,4,5],[7,6,5],[9,3,1],[5,6,7]])
d=d.reshape(3,4)
print('original array is ',d)
print('/n')
print('Transpose array is :',d.T)
print('Modified array is :')
for x in np.nditer(d[...,:1]):
    print(x)

original array is  [[3 4 5 7]
 [6 5 9 3]
 [1 5 6 7]]
/n
Transpose array is : [[3 6 1]
 [4 5 5]
 [5 9 6]
 [7 3 7]]
Modified array is :
3
6
1


In [107]:
# 2ways of storing the values in array
#1.f-style order
#2.c-style order
import numpy as np
l=np.arange(10,100,8)
l=l.reshape(3,4)
print('the original array is ')
print(l)
print('/n')
print('the modified array is ')
b=l.T
print(b)
print('/n')
print('sorted in C-style order:')
d=l.copy(order ='C')
print(d)
for x in np.nditer(d):
    print('x')
    print('\n')
print('Sorted in F-style')
g=l.copy(order='F')
print(g)
for n in np.nditer(g):
    print(n)

the original array is 
[[10 18 26 34]
 [42 50 58 66]
 [74 82 90 98]]
/n
the modified array is 
[[10 42 74]
 [18 50 82]
 [26 58 90]
 [34 66 98]]
/n
sorted in C-style order:
[[10 18 26 34]
 [42 50 58 66]
 [74 82 90 98]]
x


x


x


x


x


x


x


x


x


x


x


x


Sorted in F-style
[[10 18 26 34]
 [42 50 58 66]
 [74 82 90 98]]
10
42
74
18
50
82
26
58
90
34
66
98


In [136]:
#Broadcasting iteration
import numpy as np
h=np.arange(10,100,8)
h=h.reshape(3,4)
print('the first array is :')
print(h)
print('/n')
print('the secound array is:')
g=np.array([3,5,7,8],dtype = int)
print(g)
print('/n')
print('Modified array is: ')
for j,k in np.nditer([g,h]):
    print("%d%d"%(j,k))

the first array is :
[[10 18 26 34]
 [42 50 58 66]
 [74 82 90 98]]
/n
the secound array is:
[3 5 7 8]
/n
Modified array is: 
310
518
726
834
342
550
758
866
374
582
790
898


In [143]:
#bitwise operator
j=34
i=65
print('binary representation of a',bin(j))
print('binary representation of b',bin(i))
print('binary representation of a and b', np.bitwise_and(j,i))
#invert operator: used to caluculate the bitwise  not the operation of the given operand
print('/n')
arr=(np.array([20], dtype=np.uint8))
print("Binary operation:",np.binary_repr(30,9))
print(np.invert(arr))
print("Binary operation:",np.binary_repr(256,7))
print('left shift of 40 by 8 bits',np.left_shift(30,8))
print('binary operator 160 by 8',np.binary_repr(50,4))
print('right shift of 60 by 5',np.right_shift(60,5))

binary representation of a 0b100010
binary representation of b 0b1000001
binary representation of a and b 0
/n
Binary operation: 000011110
[235]
Binary operation: 100000000
left shift of 40 by 8 bits 7680
binary operator 160 by 8 110010
right shift of 60 by 5 1


C:\Users\pc\AppData\Local\Temp/ipykernel_4772/4142093977.py:12: DeprecationWarning: Insufficient bit width provided. This behavior will raise an error in the future.
  print("Binary operation:",np.binary_repr(256,7))
C:\Users\pc\AppData\Local\Temp/ipykernel_4772/4142093977.py:14: DeprecationWarning: Insufficient bit width provided. This behavior will raise an error in the future.
  print('binary operator 160 by 8',np.binary_repr(50,4))


In [155]:
#String Functions
'''add()
multiply()
capitalize()
title()
lower()
upper()
split()
splitlines()
strip()
strip()
join()
replace()
decode()
encode()'''
#numpy.char.add()
import numpy as np
print('Concatenating of two strings:')
print(np.char.add(['hi','guys'], [' how are you',' are u fine?']))
print(np.char.multiply(['how','do' ,'you doing','are you feeling fine?'],3))

Concatenating of two strings:
['hi how are you' 'guys are u fine?']
['howhowhow' 'dododo' 'you doingyou doingyou doing'
 'are you feeling fine?are you feeling fine?are you feeling fine?']


In [37]:
import numpy as np
print(np.char.center('python',10,'*'))
print(np.char.capitalize('python'))
print(np.char.title('welcome to python numpy'))
print(np.char.upper('welcome to warangal'))
print(np.char.lower('THE INCREDIBLES'))
print(np.char.split(('the singing legend'),sep='  ')
print(np.char.splitlines("Welcome/nTo/nBruder"))



SyntaxError: invalid syntax (Temp/ipykernel_7020/4074661096.py, line 8)

In [185]:
import numpy as np
str ='welcometowarangal'
print('original string:',str)
print('Removing the whitesapces')
print(np.char.strip(str))
print(np.char.join(':',"ABCD"))


original string: welcometowarangal
Removing the whitesapces
welcometowarangal
A:B:C:D


In [30]:
import numpy as np
str='here we came to ocean park'
print('the original string are :',str)
print("Here is the Modified string :", end =" ")
print(np.char.replace(str,'here ',''))

the original string are : here we came to ocean park
Here is the Modified string : we came to ocean park


In [42]:
import numpy as np
d=np.char.encode('james bond is near by you', 'cp500')
f=np.char.decode(d,'cp500')
d
f

array('james bond is near by you', dtype='<U25')

# Mathematical operations in numpy


In [53]:
#Trignometric functions
import numpy as np
d=np.array([34,56,789,23,45,23])
print('the original array is :')
print('applying sin', np.sin(d*np.pi/180))
print('\n')
print('now applying sine inverse', np.arcsin(d * np.pi/180))
print('\n')


the original array is :
applying sin [0.5591929  0.82903757 0.93358043 0.39073113 0.70710678 0.39073113]


now applying sine inverse [0.63529122 1.35771709        nan 0.41307297 0.90333911 0.41307297]




C:\Users\pc\AppData\Local\Temp/ipykernel_7020/2120675553.py:7: RuntimeWarning: invalid value encountered in arcsin
  print('now applying sine inverse', np.arcsin(d * np.pi/180))


In [57]:
print('the cos function in above array : is',np.cos(d *np.pi/180))
print('the inverse cos function in above array : is',np.arccos(d *np.pi/180))

the cos function in above array : is [0.82903757 0.5591929  0.35836795 0.92050485 0.70710678 0.92050485]
the inverse cos function in above array : is [0.9355051  0.21307924        nan 1.15772335 0.66745722 1.15772335]


C:\Users\pc\AppData\Local\Temp/ipykernel_7020/3889487513.py:2: RuntimeWarning: invalid value encountered in arccos
  print('the inverse cos function in above array : is',np.arccos(d *np.pi/180))


In [60]:
print('the tan function in above array : is',np.tan(d *np.pi/180))
print('Now applying  inversetan function in above array : is')
m=np.arctan(d* np.pi/180)
print('thetaninverse function in above array : is',m)


the tan function in above array : is [0.67450852 1.48256097 2.60508906 0.42447482 1.         0.42447482]
Now applying  inversetan function in above array : is
thetaninverse function in above array : is [0.53556126 0.77396152 1.49830535 0.38173485 0.66577375 0.38173485]


In [68]:
#aRounding function : numpy.around(num,decimals)
#value that returns decimal flaot point in to precision user value
import numpy as np
e=[52.3456,35.6789,45.9976,98.9431,49.999567]
print('array valueed to two decimal points: ',np.around(e,2))
print('array valueed to two decimal points: ',np.around(e,-1))
print('array valueed to two decimal points: ',np.around(e,0))

array valueed to two decimal points:  [52.35 35.68 46.   98.94 50.  ]
array valueed to two decimal points:  [ 50.  40.  50. 100.  50.]
array valueed to two decimal points:  [52. 36. 46. 99. 50.]


In [71]:
#floor:returns the floor data which is largest integer number not greater than input value
#ceil:eturns the floor data which is smallest integer number not smaller than input value
q=np.array([12.32453,45.678,345.976,678.34,67.98732])
print('the original array is:')
print('\n')
print('the modified array where  floor and ceil function is applied  :')
print(np.floor(q))
print(np.ceil(q))


the original array is:


the modified array where  floor and ceil function is applied  :
[ 12.  45. 345. 678.  67.]
[ 13.  46. 346. 679.  68.]


# Statistical Functions

In [13]:
#min(),max()
import numpy as np
d=np.array([[1,2,3,4],[5,6,7,9],[5,6,7,8,],[4,6,7,5]])
print('the highest number in the given matrix or  array is :',np.max(d))
print('the highest number in the given matrix or  array is :',np.amax(d,1))
print('the highest number in the given matrix or  array is :',np.amax(d,0))
print('the smallest number in the given matrix or  array is :',np.min(d))
print('the highest number in the given matrix or  array is :',np.amax(d,0))

the highest number in the given matrix or  array is : 9
the highest number in the given matrix or  array is : [4 9 8 7]
the highest number in the given matrix or  array is : [5 6 7 9]
the smallest number in the given matrix or  array is : 1
the highest number in the given matrix or  array is : [5 6 7 9]


In [19]:
#numpy.ptp(): used to return range of values along the axis
t=np.array([[1,2,3,4],[5,6,7,9],[5,6,7,8,],[4,6,7,5]])
print('the original array is:',t)
print('the modified array is :',np.ptp(t))
print('the modified array along with axis=0:',np.ptp(t,axis=0))
print('the modified array along with axis=1:',np.ptp(t,axis=1))

the original array is: [[1 2 3 4]
 [5 6 7 9]
 [5 6 7 8]
 [4 6 7 5]]
the modified array is : 8
the modified array along with axis=0: [4 4 4 5]
the modified array along with axis=1: [3 4 3 3]


In [27]:
#percentile(): percentages of observations in group of observation fall -np.percentile(input, q, axis):q is the percentile (1-100)
a=np.array([[1,2,3,4],[5,6,7,9],[5,6,7,8,],[4,6,7,5]])
print('the original array is :',a)
print('\n')
print('the modified array after applying percentile:',np.percentile(a,20, axis =1))
print('the resultant array after applying percentile /:',np.percentile(a,50, axis=0))


the original array is : [[1 2 3 4]
 [5 6 7 9]
 [5 6 7 8]
 [4 6 7 5]]


the modified array after applying percentile: [1.6 5.6 5.6 4.6]
the resultant array after applying percentile /: [4.5 6.  7.  6.5]


In [32]:
#numpy.median(): seprating of higher data value
c=np.array([[1,2,3,4],[5,6,7,9],[5,6,7,8,],[4,6,7,5]])
print('the original array is:',c)
print('the resultant after applying median is :',np.median(c))
print('the resultant after applying median at axis=0:',np.median(c,axis=0))
print('the resultant after applying median at axis=1 :',np.median(c,axis=1))

the original array is: [[1 2 3 4]
 [5 6 7 9]
 [5 6 7 8]
 [4 6 7 5]]
the resultant after applying median is : 5.5
the resultant after applying median at axis=0: [4.5 6.  7.  6.5]
the resultant after applying median at axis=1 : [2.5 6.5 6.5 5.5]


In [33]:
#numpy.mean():returns the arthmetic mean in given array, If the axis is given then it would calculate.
z=np.array([[1,2,3,4],[5,6,7,9],[5,6,7,8,],[4,6,7,5]])
print('the ariginal arrya is :',z)
print('the resultant mean of this rray is:',np.mean(z))
print('the resultant maean of the array at axis=0:',np.mean(z,axis=0))
print('the resultant mean of this array at axis=1:',np.mean(z,axis=1))

the ariginal arrya is : [[1 2 3 4]
 [5 6 7 9]
 [5 6 7 8]
 [4 6 7 5]]
the resultant mean of this rray is: 5.3125
the resultant maean of the array at axis=0: [3.75 5.   6.   6.5 ]
the resultant mean of this array at axis=1: [2.5  6.75 6.5  5.5 ]


In [36]:
#numpy.average
d=np.array([[1,20,34,99],[45,67.8,98,45]])
print('this is the original array :', d)
print('the average of the given array is:',np.average(d))
print('the average of the given array is:',np.average(d,axis=0))

this is the original array : [[ 1.  20.  34.  99. ]
 [45.  67.8 98.  45. ]]
the average of the given array is: 51.225
the average of the given array is: [23.  43.9 66.  72. ]


In [39]:
#numpy.std(arrayinput): std=sqrt(mean(abs(x-x.mean())**2))

s=np.array([[1,20,34,99],[45,67.8,98,45]])
print('the original array is :',s)
print('the resultant array after applying std is:',np.std(s))
print('the resultant array after applying std is:',np.std(s,axis=0))
print('the resultant array after applying std is:',np.std(s,axis=1))




the original array is : [[ 1.  20.  34.  99. ]
 [45.  67.8 98.  45. ]]
the resultant array after applying std is: 32.81926834955343
the resultant array after applying std is: [22.  23.9 32.  27. ]
the resultant array after applying std is: [36.84087404 21.75103446]


In [43]:
#variance: numpy.var(arayinput)--- formula:- mean(abs(x-x.mean())**2)
a=np.array([[1,20,34,99],[45,67.8,98,45]])
print('The original array before applying variance:',a)
print('the resultant array after applying variance:',np.var(a))
print('the resultant array after applying variance at axis=0:',np.var(a,axis=0))
print('the resultant array after applying variance at axis=1:',np.var(a,axis=1))


The original array before applying variance: [[ 1.  20.  34.  99. ]
 [45.  67.8 98.  45. ]]
the resultant array after applying variance: 1077.104375
the resultant array after applying variance at axis=0: [ 484.    571.21 1024.    729.  ]
the resultant array after applying variance at axis=1: [1357.25    473.1075]


# Sorting,searching and counting functions

In [64]:
#Sorting specifies the method to arrange data in particular order.Most of them are lexograpghical or numerical
#syntax:- numpy.sort(a, axis, kind, order)
'''a-array to be sorted
axis- th axis which the array needs to be sorted
kind:- default is quicksort
order:- if the array consists of feilds, then fields need to be sorted.
'''
import numpy as np
r=np.array([[5,6,2,1],[4,9,7,3]])
print('the original arrya is: ',r)
print('After applying sorting :',np.sort(r))
print('After applying sort function uisng axis:',np.sort(r,axis=0))
f=np.dtype([('name','S10'), ('age', int)])
g=np.array([('Vishwanth',26),('Sai',29),('Furious',9)],dtype= f)
print('the oriignal array:',g)
print('After applying sorting:',np.sort(g, order='name'))

the original arrya is:  [[5 6 2 1]
 [4 9 7 3]]
After applying sorting : [[1 2 5 6]
 [3 4 7 9]]
After applying sort function uisng axis: [[4 6 2 1]
 [5 9 7 3]]
the oriignal array: [(b'Vishwanth', 26) (b'Sai', 29) (b'Furious',  9)]
After applying sorting: [(b'Furious',  9) (b'Sai', 29) (b'Vishwanth', 26)]


In [76]:
#numpy.argsort():- returns that would sort an array, used to construct sorted array
import numpy as np
s=np.array([[12,34.5,98.7,34],[34,56.8,43.1,92.1]])
print('the original array:',s)
print('\n')
print('the resultant array is:',np.argsort(s))
print('the resultant array is:',np.argsort(s))
f=np.argsort(s)

the original array: [[12.  34.5 98.7 34. ]
 [34.  56.8 43.1 92.1]]


the resultant array is: [[0 3 1 2]
 [0 2 1 3]]
the resultant array is: [[0 3 1 2]
 [0 2 1 3]]


In [82]:
#numpy.lexsort():- it performs indirect sort using sequence of the keys.the keys cans be used as a coulmns. the function returns an index of an array, which data can be sorted
import numpy as np
s=('name','rohit','rahul','wohinsie')
d=('six.t','seven.t','seven.t', 'sis.t')
g=np.lexsort((d,s))
print(g)
print([s[1]+' '+d[2] for i in g])
print([s[2]+' '+d[1] for  m in g])

[0 2 1 3]
['rohit seven.t', 'rohit seven.t', 'rohit seven.t', 'rohit seven.t']
['rahul seven.t', 'rahul seven.t', 'rahul seven.t', 'rahul seven.t']


In [84]:
#numpy.nonzero():- returns the indices of non-zero elements in input array.
import numpy as np
r=np.array([[1,20,0],[45,0,50],[45,67,80]])
print('the original array is :',r)
print('\n')
print('after applying nonzero function',np.nonzero(r))

the original array is : [[ 1 20  0]
 [45  0 50]
 [45 67 80]]


after applying nonzero function (array([0, 0, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 0, 2, 0, 1, 2], dtype=int64))


In [97]:
#numpy.argmin()
#numpy.argwhere()
#numpy.flatnonzero()
#numpy.where()
#numpy.searchsorted()
#numpy.extract()
print('after applying argmin function',np.argmin(r))
print('after applying argwhere function',np.argwhere(r))
print('after applying flatnonzero function',np.flatnonzero(r))
print('after applying where function',np.where(r))
a=np.count_nonzero(([20,0,40,50],[30,40,0,32]))
u=np.count_nonzero(([30,49,56,0],[59,0,34,2]))
print('Number of non-zero values:',a)
print('Number of non-zero values:',u)

after applying argmin function 2
after applying argwhere function [[0 0]
 [0 1]
 [1 0]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]
after applying flatnonzero function [0 1 3 5 6 7 8]
after applying where function (array([0, 0, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 0, 2, 0, 1, 2], dtype=int64))
Number of non-zero values: 6
Number of non-zero values: 6


In [6]:
import numpy as np
s=np.arange(8)
print('the original aray is :',s)
print('the id of a,id:',id(s))
p=s
print('the id of p, :',id(p))
print('change the shape of p')
p.shape=4,2
print(p)
print('change of shape for s',np.shape(s))

the original aray is : [0 1 2 3 4 5 6 7]
the id of a,id: 1932483448704
the id of p, : 1932483448704
change the shape of p
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
change of shape for s (4, 2)


In [18]:
#ndarray.view in numpy is a very new object look at same data of riginal array and view doesnot own the data
import numpy as np
e=np.arange(16).reshape(4,4)
print('Array is:',e)
print('create the view of array')
y=e.view()
print(y)
print('id() for both array are different:')
print('id() of a is:',id(y))
print('id() of a is:',id(e))
#changinfg the shape of the array


Array is: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
create the view of array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
id() for both array are different:
id() of a is: 1932483405504
id() of a is: 1932483512960


In [24]:
#DEEP COPY()
#ndarray.copy():- copies new array and  copy it's own data and doesn't share with the original array
import numpy as np
s=np.array([[12,12],[34,56],[78,98],[56,43],[56,21]])
print('original array is:',s)
print('\n')
o=s.copy()
print('the mo dified and copied aray is :', np.copy(s))
print(' o is equa;l to s ', o is s)
print('chnage of contents of o')
o[0,0]=100
print('the modified array  of o:',o)
print(s)

original array is: [[12 12]
 [34 56]
 [78 98]
 [56 43]
 [56 21]]


the mo dified and copied aray is : [[12 12]
 [34 56]
 [78 98]
 [56 43]
 [56 21]]
 o is equa;l to s  False
chnage of contents of o
the modified array  of o: [[100  12]
 [ 34  56]
 [ 78  98]
 [ 56  43]
 [ 56  21]]
[[12 12]
 [34 56]
 [78 98]
 [56 43]
 [56 21]]


In [48]:
#Numpy.matlib.empty() function:- the function is used to retunrs a matrix instead of ndarray objects.
#numpy.matlib.empty(shape, dtype, order) :- shape- int or tuple of int defining the shape of the matrix.Object:- insertion order of the matrix Cor F
import numpy.matlib
import numpy as np
#fill empty array with some random data
print('using random function:',np.matlib.rand(4,4))
print('\n')
#empty()
print('using empty function:')
print(np.matlib.empty((4,4)))
print('\n')
#zeros()
print('the zero function is:, ',np.matlib.zeros((3,3)))
#numpy.matlib.ones()
print('\n')
import numpy as np
import numpy.matlib
print('the ones function:',numpy.matlib.ones((2,2)))
#numpy.matlib.eye(n,M,k,dtype)(n-rows,M(capital)-coulmns,k-index of the diagonal, dtype)
print('\n')
print('here using this eyes method we can form or create the identity matrix:',np.matlib.eye(n=4,M=4,k=0, dtype=float))

using random function: [[0.18282244 0.34217936 0.02603144 0.21007885]
 [0.65992855 0.91691933 0.60384063 0.84446423]
 [0.19702197 0.22418051 0.77549192 0.94008564]
 [0.87790163 0.8349056  0.61613973 0.24483177]]


using empty function:
[[0.18282244 0.34217936 0.02603144 0.21007885]
 [0.65992855 0.91691933 0.60384063 0.84446423]
 [0.19702197 0.22418051 0.77549192 0.94008564]
 [0.87790163 0.8349056  0.61613973 0.24483177]]


the zero function is:,  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


the ones function: [[1. 1.]
 [1. 1.]]


here using this eyes method we can form or create the identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Linear algebra

In [71]:
#numpy.linalg()
#numpy.dot():- applying dot between two matrices.
d=np.array([[23,45],[90,12]])
e=np.array([[45,67],[12,32]])
print('this is the matrix d',d)
print('this is the matrix e',e)
dot=np.dot(d,e)
print('the resultant:',dot)
print('\n')
#numpy.vdot()
print('calling the original matrices:', d,e)
print('After applying vdot function:', np.vdot(d,e))
#numpy.inner():-'After aplying the inner() which is sum of product of INNER elements in one dimension.It returns the sum of product of elements over the last axis
print('\n')
print('before aplying the inner():',d,e)
print('After aplying the inner() which is sum of product of INNER elements in one dimension:',np.inner(d,e))
#nump.matmul(): multiplying two matrices. the order must mtach orelse it will give an error
print('\n')
print('before applying two matrices:',d,e)
print('after multiplying of two matrices:',np.matmul(d,e))
#numpy.determinant function():- it will calculate the difference of product diagonal elements, ad-bc
print('\n')
print('before applying determinant in both matrices:',d,e)
print('after applying determinant in matrices:', np.linalg.det(d))
#numpy.linalg.solve():-this fuction is used solvethe qudratic function where the values are given in matrix form
print('\n')
print('the original array is :',d,e)
print('after applying :',np.linalg.solve(d,e))
#numpy.linalg.inv():-multiplicative of inverse matrices
print('\n')
print('the original array is:',d,e)
print('after applying the inverse function',np.linalg.inv(d))
print('after applying the inverse function',np.linalg.inv(e))

this is the matrix d [[23 45]
 [90 12]]
this is the matrix e [[45 67]
 [12 32]]
the resultant: [[1575 2981]
 [4194 6414]]


calling the original matrices: [[23 45]
 [90 12]] [[45 67]
 [12 32]]
After applying vdot function: 5514


before aplying the inner(): [[23 45]
 [90 12]] [[45 67]
 [12 32]]
After aplying the inner() which is sum of product of INNER elements in one dimension: [[4050 1716]
 [4854 1464]]


before applying two matrices: [[23 45]
 [90 12]] [[45 67]
 [12 32]]
after multiplying of two matrices: [[1575 2981]
 [4194 6414]]


before applying determinant in both matrices: [[23 45]
 [90 12]] [[45 67]
 [12 32]]
after applying determinant in matrices: -3774.0


the original array is : [[23 45]
 [90 12]] [[45 67]
 [12 32]]
after applying : [[0.         0.16852146]
 [1.         1.4027557 ]]


the original array is: [[23 45]
 [90 12]] [[45 67]
 [12 32]]
after applying the inverse function [[-0.00317965  0.01192369]
 [ 0.02384738 -0.00609433]]
after applying the inverse function [[ 